CREATE TABLE `audit_logs` (
	`id` varchar(64) NOT NULL,
	`action` enum('create','update','delete','print','close_day','approve_close','reject_close','permission_change','login','logout') NOT NULL,
	`entityType` enum('customer','card','operation','expense','salary','employee','daily_close','treasury','system') NOT NULL,
	`entityId` varchar(64),
	`userId` varchar(64) NOT NULL,
	`userName` text NOT NULL,
	`timestamp` timestamp NOT NULL DEFAULT (now()),
	`details` json,
	`ipAddress` varchar(45),
	`userAgent` text,
	CONSTRAINT `audit_logs_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `cards` (
	`transactionId` varchar(64) NOT NULL,
	`name` text NOT NULL,
	`nationalId` varchar(64) NOT NULL,
	`passportNumber` varchar(64) NOT NULL,
	`passportExpiry` varchar(20) NOT NULL,
	`accountNumber` varchar(64) NOT NULL,
	`iban1` varchar(64) NOT NULL,
	`iban2` varchar(64),
	`accountPhone` varchar(20) NOT NULL,
	`personalPhone` varchar(20) NOT NULL,
	`cardNumber` varchar(64) NOT NULL,
	`cardExpiry` varchar(20) NOT NULL,
	`cardPin` varchar(20) NOT NULL,
	`purchasePrice` decimal(10,2) NOT NULL,
	`delegate` varchar(100) NOT NULL,
	`delegateShare` decimal(10,2) NOT NULL,
	`totalPurchasePrice` decimal(10,2) NOT NULL,
	`documentsReceived` json NOT NULL,
	`depositAmount` decimal(10,2) NOT NULL DEFAULT '0',
	`currencyReserveAmount` decimal(10,2) NOT NULL DEFAULT '0',
	`bankDollarCost` decimal(10,4) NOT NULL DEFAULT '0',
	`cardDollarValue` decimal(10,2) NOT NULL DEFAULT '0',
	`firstWithdrawalRate` decimal(5,2) NOT NULL DEFAULT '0',
	`firstNetAmount` decimal(10,2) NOT NULL DEFAULT '0',
	`remainingInCard` decimal(10,2) NOT NULL DEFAULT '0',
	`sellDollarPrice` decimal(10,4) NOT NULL DEFAULT '0',
	`firstDinarValue` decimal(10,2) NOT NULL DEFAULT '0',
	`firstProfit` decimal(10,2) NOT NULL DEFAULT '0',
	`secondWithdrawalRate` decimal(5,2) NOT NULL DEFAULT '0',
	`secondNetAmount` decimal(10,2) NOT NULL DEFAULT '0',
	`secondSellDollarPrice` decimal(10,4) NOT NULL DEFAULT '0',
	`secondDinarValue` decimal(10,2) NOT NULL DEFAULT '0',
	`secondProfit` decimal(10,2) NOT NULL DEFAULT '0',
	`totalProfit` decimal(10,2) NOT NULL DEFAULT '0',
	`financialStatus` text NOT NULL,
	`documentStatus` text NOT NULL,
	`financialStatusHistory` json NOT NULL,
	`documentStatusHistory` json NOT NULL,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	`createdBy` varchar(64) NOT NULL,
	`updatedBy` varchar(64) NOT NULL,
	CONSTRAINT `cards_transactionId` PRIMARY KEY(`transactionId`)
);
--> statement-breakpoint
CREATE TABLE `customers` (
	`id` varchar(64) NOT NULL,
	`transactionNumber` varchar(64) NOT NULL,
	`name` text NOT NULL,
	`phone` varchar(20) NOT NULL,
	`email` varchar(320),
	`idNumber` varchar(64),
	`idType` enum('national_id','passport','driver_license') NOT NULL,
	`address` text,
	`city` varchar(100),
	`passportNumber` varchar(64),
	`passportExpiry` varchar(20),
	`accountNumber` varchar(64),
	`iban1` varchar(64),
	`iban2` varchar(64),
	`accountPhone` varchar(20),
	`personalPhone` varchar(20),
	`cardNumber` varchar(64),
	`cardExpiry` varchar(20),
	`cardPin` varchar(20),
	`purchasePrice` decimal(10,2),
	`delegate` varchar(100),
	`delegateShare` decimal(10,2),
	`totalPrice` decimal(10,2),
	`documentsReceived` json,
	`documents` json,
	`registrationDate` timestamp NOT NULL DEFAULT (now()),
	`operationStatus` enum('purchased','awaiting_match','matched','not_matched','reserved','deposited','awaiting_execution','executed','partial_withdrawal','full_withdrawal','ready_for_pickup') NOT NULL,
	`documentStatus` enum('cannot_deliver','passport_delivered','pin_delivered','card_delivered','card_pin_delivered','passport_card_delivered','passport_pin_delivered','all_delivered') NOT NULL,
	`totalBalance` decimal(10,2) NOT NULL DEFAULT '0',
	`totalTransactions` int NOT NULL DEFAULT 0,
	`lastTransactionDate` timestamp,
	`notes` text,
	`createdBy` varchar(64) NOT NULL,
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `customers_id` PRIMARY KEY(`id`),
	CONSTRAINT `customers_transactionNumber_unique` UNIQUE(`transactionNumber`)
);
--> statement-breakpoint
CREATE TABLE `employees` (
	`id` varchar(64) NOT NULL,
	`employeeCode` varchar(64) NOT NULL,
	`phone` varchar(20) NOT NULL,
	`fullName` text NOT NULL,
	`jobTitle` enum('data_entry','operations','supervisor','deputy_manager','accountant','manager') NOT NULL,
	`passwordHash` text NOT NULL,
	`status` enum('active','disabled') NOT NULL DEFAULT 'active',
	`permissions` json NOT NULL,
	`salary` decimal(10,2),
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`createdBy` varchar(64) NOT NULL,
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	`updatedBy` varchar(64),
	CONSTRAINT `employees_id` PRIMARY KEY(`id`),
	CONSTRAINT `employees_employeeCode_unique` UNIQUE(`employeeCode`),
	CONSTRAINT `employees_phone_unique` UNIQUE(`phone`)
);
--> statement-breakpoint
CREATE TABLE `treasury_records` (
	`id` varchar(64) NOT NULL,
	`type` enum('capital','revenue','expense','profit','withdrawal','deposit') NOT NULL,
	`amount` decimal(10,2) NOT NULL,
	`currency` enum('LYD','USD','USDT') NOT NULL DEFAULT 'LYD',
	`description` text NOT NULL,
	`category` varchar(100),
	`reference` varchar(100),
	`timestamp` timestamp NOT NULL DEFAULT (now()),
	`processedBy` varchar(64) NOT NULL,
	`notes` text,
	CONSTRAINT `treasury_records_id` PRIMARY KEY(`id`)
);
